### ISSUE TITLE
issue with 1.17

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/golang-builder#155]
go: downloading github.com/pkg/errors v0.8.1
2021/08/31 12:22:01 processing 1.16
2021/08/31 12:22:01 no version change for Go 1.16.7
2021/08/31 12:22:01 processing 1.17
2021/08/31 12:22:01 failed to detect current version of 1.17: couldn't get exact version for 1.17
exit status 1

**Comment by SuperQ** [comment]
Yea, I've been working on this a bit. There's a bunch of incorrect assumptions in regexps.
