### ISSUE TITLE
`gotestsum` not present in 1.17

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/golang-builder#164]
Starting with the PR that introduced the 1.17 builder image into prometheus/prometheus, test results haven't been uploaded, instead rendering this [error](https://app.circleci.com/pipelines/github/prometheus/prometheus/13232/workflows/08ce33d4-4c15-439a-817c-6a7ede518814/jobs/59538/parallel-runs/0/steps/0-112):

```
Unable to save test results from /root/project/test-results
Error error accessing path "/root/project/test-results": stat /root/project/test-results: no such file or directory
Found no test results, skipping
```

As can be seen from [this run](https://app.circleci.com/pipelines/github/prometheus/prometheus/13117/workflows/f81fda2c-7fd5-4731-969b-03db7bdbf921/jobs/58750/parallel-runs/0/steps/0-113) about a week earlier, this error didn't appear with the 1.16 builder image.

This is because `gotestsum` is somehow no longer present in 1.17.

```
>> running all tests
GO111MODULE=on gotestsum --junitfile test-results/unit-tests.xml -- -race -p 2 ./...
```
(1.16)

```
>> running all tests
GO111MODULE=on go test -race -p 2 ./...
```
(1.17)

https://github.com/prometheus/prometheus/blob/c564984daa96a9f49ab6dc3c3db9b29b580cae38/Makefile.common#L72-L79

**Comment by LeviHarrison** [comment]
cc @SuperQ

**Comment by simonpasquier** [comment]
thanks for pointing this out, I've submitted #169
