### ISSUE TITLE
Deduplicate builder.sh

### ISSUE THREAD

**Issue by discordianfish** [prometheus/golang-builder#18]
Not sure I fully understand the intend, but we have builder.sh in both the base image as well as in main and the platform specific variants. Since the script has platform specific conditions I'm wondering whether we can just have one in the base image? Or what is the reason to have one per arch?

/cc @sdurrheimer

**Comment by sdurrheimer** [comment]
The base image can be used to do non-cgo compile, so there is a `builder.sh` script for that.
Other images inherite from the base image but redefine the `builder.sh` script to handle corresponding architectures.

**Comment by SuperQ** [comment]
I'm consolidating the CGO/crossbuild arch builds in https://github.com/prometheus/golang-builder/pull/119. This cleans up a lot of the duplication.

**Comment by discordianfish** [comment]
I'll close this then
