### ISSUE TITLE
Cannot crossbuild with promu with latest golang-builder images

### ISSUE THREAD

**Issue by bsosnader** [prometheus/golang-builder#185]
After this change to the golang-builder base image 1.18: https://quay.io/repository/prometheus/golang-builder?tab=history&tag=latest on June 8, any crossbuilds with promu that utilize the golang-builder image is completely broken. The container cannot start:

 > build
> bash build_ui.sh --all
build module/lezer-promql
make: *** [Makefile:48: ui-build] Error 243
!! The base builder docker image exited unexpectedly: exit status 2

This is on debian linux. I ran `promu crossbuild -p windows/amd64` as well as linux/amd64, both failed with same error.

**Comment by roidelapluie** [comment]
We have a workaround in main. See https://github.com/npm/cli/issues/4996 for the root cause.

Our workaround: https://github.com/prometheus/prometheus/pull/10843

**Comment by bsosnader** [comment]
thanks!

**Comment by SuperQ** [comment]
Oh, I wonder if we should fix this by setting the ENV var in the golang-builder image.
