### ISSUE TITLE
Upgrade base to Debian bookworm

### ISSUE THREAD

**Issue by SuperQ** [prometheus/golang-builder#197]
Debian 12 / bookworm is expected sometime in 2023. There are some TODO items.

## riscv64
Add packages:
* `libasan6-riscv64-cross`
* `libitm1-riscv64-cross`
* `libubsan1-riscv64-cross`

**Comment by boosterl** [comment]
I have taken a look at this, and it seems `libasan6-riscv64-cross` will be available in bookworm. So the current status is:

- [x] libasan6-riscv64-cross (available in [bookworm](https://packages.debian.org/bookworm/libasan6-riscv64-cross))
- [ ] libitm1-riscv64-cross
- [ ] libubsan1-riscv64-cross

I did also however notice that `crossbuild-essential-riscv64` is available in the [Ubuntu packages](https://packages.ubuntu.com/kinetic/crossbuild-essential-riscv64). There `libitm1-riscv64-cross` and `libubsan1-riscv64-cross` is not a dependency (and they are also not packaged).

**Comment by SuperQ** [comment]
It looks like none of these packages made it into the final bookworm release.

**Comment by SuperQ** [comment]
It looks like there is `libasan8-riscv64-cross` in bookworm.

**Comment by SuperQ** [comment]
Upgrade to bookworm. No package changes: https://github.com/prometheus/golang-builder/pull/222
