### ISSUE TITLE
common.sh file not present under '1.6/arm/rootfs/' dir

### ISSUE THREAD

**Issue by taherbohari** [prometheus/golang-builder#20]
The script 'builder.sh' under 1.6/arm/rootfs folder has mentioned 'common.sh' file as source. But there is no file present under '1.6/arm/rootfs/' dir.

**Comment by sdurrheimer** [comment]
The `1.6/arm` image extend the `1.6/base` image, you can find the `common.sh` script [here](https://github.com/prometheus/golang-builder/blob/master/1.6/base/rootfs/common.sh).

**Comment by taherbohari** [comment]
thanks @sdurrheimer
