### ISSUE TITLE
Does this support PowerPC 32bit？

### ISSUE THREAD

**Issue by oska874** [prometheus/golang-builder#34]
I'm trying to compile a go program to run on PowerPC (made by freescale,running in 32bit,big endian). As I can see in your guide, the powerpc environment you use is ppc 64bit little endian.
Does your docker image support  PowerPC 32bit big endian?

**Comment by grobie** [comment]
No, because the go programming language doesn't support PowerPC 32bit. Unfortunately, you won't be able to use any go / Prometheus programs on this architecture.
