### ISSUE TITLE
debian:buster instead of :stable to allow for s390x builds

### ISSUE THREAD

**Issue by gouthamve** [prometheus/golang-builder#48]
From https://groups.google.com/forum/#!msg/prometheus-developers/ZjWZR1kVMbg/Ym2fa43iBgAJ

They'd like to contribute building binaries for `s390x` but they require `debian:buster` because it provides `crossbuild-essentials-s390x`.

Thoughts on moving to `:buster` @SuperQ @sdurrheimer @grobie?

**Comment by SuperQ** [comment]
`crossbuild-essential-s390x` is a meta-package for `dpkg-cross`, `g++-s390x-linux-gnu`, and `gcc-s390x-linux-gnu`. We should be able to use those directly in stable.

**Comment by simonpasquier** [comment]
It looks like this issue has been fixed since now...
