### ISSUE TITLE
Tests fail for pull requests from forked repositories

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/golang-builder#52]
Reported from https://github.com/prometheus/golang-builder/pull/51#issuecomment-419461724

The CI failed because OSXCROSS_SDK_URL isn't set (https://circleci.com/gh/prometheus/golang-builder/165). This relates probably to the migration from Circle CI 1.0 to 2.0 and the fact that by default, builds from forked pull requests can't access secrets (see https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests).

_Not sure what is the fix for this problem._

**Comment by sdurrheimer** [comment]
@SuperQ It is, Apple license doesn't allow to distribute the SDK publicly.

**Comment by SuperQ** [comment]
Since the OSX SDK is not public, we need to keep the location private. I guess this means we will have to ignore test failures for fork PRs.
